# Generated by Django 5.0 on 2023-12-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencias',
            name='fecha',
            field=models.DateField(auto_created=True),
        ),
    ]
