# Generated by Django 5.0 on 2023-12-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0002_alter_transferencias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencias',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
