# Generated by Django 5.0 on 2023-12-09 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferencias', '0004_remove_cuenta_nombre_cuenta_tipo_cuenta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuariopersonalizado',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='tipo_cuenta',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(default='pesos', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cliente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='transferencias.cliente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferencias.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=16)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferencias.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='Transferencia',
        ),
        migrations.DeleteModel(
            name='UsuarioPersonalizado',
        ),
    ]
